# Generated by Django 6.0.7 on 2026-07-30 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('youtube', 'YouTube'), ('instagram', 'Instagram')], max_length=20)),
                ('file_size', models.IntegerField(default=0)),
                ('url', models.URLField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('real', 'Real'), ('fake', 'AI Generated')], default='unknown', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('probability_real', models.FloatField(default=0.0)),
                ('probability_fake', models.FloatField(default=0.0)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('media', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detector.media')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('detection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detector.detection')),
            ],
        ),
    ]
